# Generated by Django 5.2.17 on 2026-10-08 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], max_length=20)),
                ('institutional_id', models.CharField(max_length=50, unique=True)),
                ('graduation_term', models.CharField(blank=True, max_length=50)),
                ('id_front', models.FileField(upload_to='institutional_ids/')),
                ('id_back', models.FileField(upload_to='institutional_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
