# Generated by Django 5.2.17 on 2026-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodorder_claimed_at_foodorder_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='KYC approved'),
        ),
    ]
